version: '3.7'

services:
  postgres:
    build: ./docker/dev/images/postgres
    container_name: postgres-dev
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    volumes:
      - ./scripts/dev/postgres/init.sh:/docker-entrypoint-initdb.d/init.sh
      - postgres_data:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432

volumes:
  postgres_data: {}